baseurl: ""
url: ""

permalink: simple
timezone: America/New_York

pagination:
  enabled: true
  per_page: 10

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

svg:
  optimize: true
